app.value('selects', {
    term:{
        'terms':'terms',
        'terms/contexts':'terms/contexts',
        'terms/similar_terms':'terms/similar_terms'
    },
    text:{
        'text':'text',
        'text/keywords':'text/keywords',
        'text/tokenize':'text/tokenize',
        'text/slices':'text/slices',
        'text/bulk':'text/bulk',
        'text/detect_language':'text/detect_language'
    },
    expression:{
        'expressions':'expressions',
        'expressions/contexts':'expressions/contexts',
        'expressions/similar_terms':'expressions/similar_terms',
        'expressions/bulk':'expressions/bulk',
        'expressions/contexts/bulk':'expressions/contexts/bulk',
        'expressions/similar_terms/bulk':'expressions/similar_terms/bulk'
    },
    image:{
        'image':'image',
        'image/compare':'image/compare',
        'image/bulk':'image/bulk'
    }
});